name: terraform
on:
  workflow_dispatch:
    inputs:
      rds_deployment:
        description: 'Choose the RDS deployment option.'
        required: true
        default: ''
        type: choice
        options:
          - test-module
          - single-az-instance
          - multi-az-instance
          - multi-az-db-cluster
env:
# Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./${{inputs.rds_deployment}}
    steps:
      - name: version
        run: terraform -v
      - name: initialize
        run: terraform init
      - name: validate
        run: terraform validate
      - name: plan
        run: terraform plan
