name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch
jobs:
  check-directory-files-and-folders:
    runs-on: self-hosted
    steps:
      - run: ls
